import type { ModelConfigCopy } from '@nimiplatform/kit/features/model-config';

export const STORYBOOK_MODEL_CONFIG_COPY: ModelConfigCopy = {
  title: 'AI 模型',
  description: '配置 Storybook 文本生成的可移植 Runtime 意图。',
  backLabel: '返回',
  activeModelLabel: '当前配置',
  activeModelHint: '查看或更改 Runtime 路由意图',
  activeModelConfiguredLabel: '已配置',
  activeModelSetupPendingLabel: '待配置',
  modelPickerTitle: '选择 Runtime 路由',
  modelPickerSearchPlaceholder: '搜索',
  modelPickerLoadingLabel: '正在加载…',
  modelPickerEmptyLabel: '没有可用选项',
  configuredSummary: '已保存 Runtime 路由意图。',
  emptySummary: '尚未配置文本生成。',
  routeLabel: '路由',
  localLabel: '本地',
  cloudLabel: '云端',
  saveLocalLabel: '使用本地 Runtime',
  saveCloudLabel: '保存云端意图',
  savingLabel: '正在保存…',
  advancedLabel: '高级意图',
  advancedHint: '这些值是可移植请求意图，不指定 provider 或 model。',
  requiredFeaturesLabel: '必需功能',
  requiredFeaturesPlaceholder: '每行一个',
  defaultsLabel: '生成默认值',
  defaultsPlaceholder: '{"temperature":0.7,"topP":1,"maxTokens":1024}',
  localChoiceDescription: 'Runtime 在执行时验证本机选择。',
  localSelectedLabel: '已选择本地 Runtime 意图',
  localMissingLabel: '需要在 Nimi 中配置本机模型',
  localBrokenLabel: '本机模型配置不可用',
  localUnavailableLabel: '当前无法读取本机模型配置',
  openMachineLabel: '在 Nimi 中配置',
  loadFailed: '无法读取 AI 配置。',
  saveFailed: '无法保存 AI 配置。',
  retryLabel: '重试',
  technicalDetailsLabel: '技术详情',
  unsupportedCapabilityLabel: '不支持的能力',
  notConfiguredLabel: '未配置',
  configuredLabel: '已配置',
  selectionRequiredLabel: '需要配置',
  blockedLabel: '受阻',
  mismatchLabel: '功能不匹配',
  cancelLabel: '取消',
  confirmSelectionLabel: '确认选择',
  capabilityLabel: (capabilityContract, fallback) => (
    capabilityContract === 'text.generate' ? '叙事文本生成' : fallback
  ),
  capabilityDescription: (capabilityContract, fallback) => (
    capabilityContract === 'text.generate'
      ? '用于 Bible 草案、场景文本和选择建议。'
      : fallback
  ),
};
