export const STORYBOOK_MODEL_CONFIG_COPY: Readonly<Record<string, string>> = {
  'ModelConfig.profile.sectionTitle': 'AI 配置档案',
  'ModelConfig.profile.summaryLabel': 'AI Profile',
  'ModelConfig.profile.emptySummaryLabel': '未应用 Profile',
  'ModelConfig.profile.applyButtonLabel': '应用 Profile',
  'ModelConfig.profile.changeButtonLabel': '更换',
  'ModelConfig.profile.manageButtonTitle': '管理 AI Profile',
  'ModelConfig.profile.modalTitle': '应用 AI Profile',
  'ModelConfig.profile.modalHint': '应用 Profile 会覆盖当前能力绑定。请确认后再写入。',
  'ModelConfig.profile.loadingLabel': '正在加载 Profile...',
  'ModelConfig.profile.emptyLabel': '暂无可用 Profile。',
  'ModelConfig.profile.currentBadgeLabel': '当前',
  'ModelConfig.profile.cancelLabel': '取消',
  'ModelConfig.profile.confirmLabel': '确认应用',
  'ModelConfig.profile.applyingLabel': '应用中...',
  'ModelConfig.profile.reloadLabel': '重新加载',
  'ModelConfig.profile.importLabel': '导入 AI Profile',
  'ModelConfig.profile.previewTitle': '确认配置变更',
  'ModelConfig.profile.previewHint': '这里展示写入前后的完整 AIConfig 差异。确认前不会保存。',
  'ModelConfig.profile.previewFirstApplyLabel': '当前 scope 还没有 AIConfig；应用后会创建配置。',
  'ModelConfig.profile.previewNoChangeLabel': '这个 Profile 与当前配置一致。',
  'ModelConfig.profile.previewBeforeLabel': '当前',
  'ModelConfig.profile.previewAfterLabel': '应用后',
  'ModelConfig.profile.previewWarningsLabel': '警告',
  'ModelConfig.profile.previewConfirmLabel': '确认写入',
  'ModelConfig.profile.previewBackLabel': '返回',
  'ModelConfig.section.chat.title': '文本生成',
  'ModelConfig.capability.textGenerate.title': '叙事生成模型',
  'ModelConfig.capability.textGenerate.subtitle': 'Storybook Runtime AI',
  'ModelConfig.capability.textGenerate.detail': '为 Bible 草案、场景文本和选择建议绑定 Runtime text.generate 模型。缺少绑定时生成会 fail-close。',
  'ModelConfig.editor.common.timeoutLabel': '超时',
  'ModelConfig.editor.common.defaultPlaceholder': '默认',
  'ModelConfig.editor.common.previewBadgeLabel': '预览',
  'ModelConfig.editor.textGenerate.parametersLabel': '参数',
  'ModelConfig.editor.textGenerate.generationDefaultsLabel': '生成默认值',
  'ModelConfig.editor.textGenerate.responseControlsLabel': '响应控制',
  'ModelConfig.editor.textGenerate.advancedLabel': '高级设置',
  'ModelConfig.editor.textGenerate.temperatureLabel': 'Temperature',
  'ModelConfig.editor.textGenerate.topPLabel': 'Top P',
  'ModelConfig.editor.textGenerate.topKLabel': 'Top K',
  'ModelConfig.editor.textGenerate.maxTokensLabel': 'Max Tokens',
  'ModelConfig.editor.textGenerate.stopSequencesLabel': '停止序列',
  'ModelConfig.editor.textGenerate.stopSequencesHint': '最多 {{max}} 条，每行一条。',
  'ModelConfig.editor.textGenerate.stopSequencesPlaceholder': '输入后回车',
  'ModelConfig.editor.textGenerate.presencePenaltyLabel': 'Presence penalty',
  'ModelConfig.editor.textGenerate.frequencyPenaltyLabel': 'Frequency penalty',
  'ModelConfig.hub.title': 'AI 模型',
  'ModelConfig.hub.backLabel': '返回',
  'ModelConfig.hub.aggregateReady': '{{count}} 项已就绪',
  'ModelConfig.hub.aggregateAttention': '{{count}} 项需要配置',
  'ModelConfig.hub.aggregateNeutral': '{{count}} 项未配置',
  'ModelConfig.hub.aggregateEmpty': '暂无能力配置',
  'ModelConfig.hub.detailTitleFormat': '{{section}}配置',
  'ModelConfig.hub.activeModelLabel': '当前模型',
  'ModelConfig.hub.detailStatusReady': 'Runtime 已就绪',
  'ModelConfig.hub.detailStatusAttention': '需要配置',
  'ModelConfig.hub.detailStatusNeutral': '未配置',
};

export function translateStorybookModelConfig(
  key: string,
  vars?: Readonly<Record<string, string | number>>,
): string {
  const fallback = typeof vars?.defaultValue === 'string' ? vars.defaultValue : key;
  const template = STORYBOOK_MODEL_CONFIG_COPY[key] || fallback;
  if (!vars) return template;
  return Object.entries(vars).reduce(
    (current, [name, value]) => current.replaceAll(`{{${name}}}`, String(value)),
    template,
  );
}
